language: php

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

php:
  - 7.2
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1 DEFAULT=0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p --standard=PSR12 ./src ./tests; fi

after_success:
  - |
      if [[ $DEFAULT == 1 ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi
